package com.mni.api.customer;

import com.mni.api.validation.ClientType;
import com.mni.api.validation.Password;
import com.mni.model.customer.Customer;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;
import javax.validation.constraints.Size;

/**
 * Created by will.schick on 6/17/19.
 */
@ApiModel(description="DTO for Customers. Does not include entitlements, which have separate endpoints which take/return Collections of EntitlementDtos." +
        "\nNOTE: clientType field represents the type of customer. It can be 'c' for Client, 'r' for Reporter, or 'a' for Administrator.")
public class CustomerDto {

    @ApiModelProperty(value="Autogenerated ID for reference to customer (used in GET, PUT, " +
            "and DELETE requests). Attempting to set a customer's ID has no effect.")
    private Long id;

    @NotBlank
    @Size(max = Customer.MAX_NAME_LENGTH, message = "Name cannot be over " +
            Customer.MAX_NAME_LENGTH + " characters long")
    @ApiModelProperty(value="Human-readable name describing the customer. " +
            "Cannot be blank (a null string, empty string, or string of just " +
            "whitespace is blank).",
            required = true,
            allowableValues = "range[1, 100]",
            example="ACME")
    private String name;

    @NotBlank
    @Size(max = Customer.MAX_USERID_LENGTH, message = "User ID cannot be over " +
            Customer.MAX_USERID_LENGTH + " characters long")
    @ApiModelProperty(value="User ID that the customer uses to login. " +
            "Cannot be blank (a null string, empty string, or string of just " +
            "whitespace is blank).",
            required = true,
            allowableValues = "range[1, 20]",
            example="acme")
    private String userId;

    @NotBlank
    @Size(min = Customer.MIN_PASSWORD_LENGTH, max = Customer.MAX_PASSWORD_LENGTH, message = "Password must" +
            " be between " + Customer.MIN_PASSWORD_LENGTH + " and " + Customer.MAX_PASSWORD_LENGTH +
            " characters long")
    @Password
    @ApiModelProperty(value="Password that the customer uses to login. " +
            "Must have a lowercase letter, uppercase letter, number, and special character.",
                        required = true,
                        allowableValues = "range[15, 100]",
                        example="a!r4#$rEfa12Rmf*")
    private String password;

    @NotNull
    @ClientType
    @ApiModelProperty(required = true,
                        value="Type of client. Can be 'c' for client, 'r' for reporter, " +
                                "or 'a' for administrator.")
    private Character clientType;

    @NotNull
    @Positive
    @ApiModelProperty(allowableValues = "range[1,infinity]",
                        required = true,
                        value="Priority of customer within a group (used in config files). " +
                              "1 is highest priority, with larger numbers being lower priority.")
    private Integer priority;

    @ApiModelProperty(value = "Defaults to false. Disabled customers retain entitlements but " +
            "are not considered in config files, effectively not receiving any data.")
    private boolean disabled;

    public CustomerDto() {}

    public CustomerDto(Long id, String name, String userId, String password,
                       Character clientType, Integer priority) {
        this.id = id;
        this.name = name;
        this.userId = userId;
        this.password = password;
        this.clientType = clientType;
        this.priority = priority;
    }

    public static CustomerDto translateCustomerToCustomerDto(Customer customer){
        if(customer == null) return null;
        CustomerDto customerDto = new CustomerDto();
        customerDto.setId(customer.getId());
        customerDto.setName(customer.getName());
        customerDto.setUserId(customer.getUserId());
        customerDto.setPassword(customer.getPassword());
        customerDto.setClientType(customer.getClientType());
        customerDto.setPriority(customer.getPriority());
        customerDto.setDisabled(customer.isDisabled());
        return customerDto;
    }

    // Translates CustomerDto object to Customer object
    public static Customer translateCustomerDtoToCustomer(CustomerDto customerDto) {
        if(customerDto == null) return null;
        Customer customer = new Customer();
        customer.setId(customerDto.getId());
        customer.setName(customerDto.getName());
        customer.setUserId(customerDto.getUserId());
        customer.setPassword(customerDto.getPassword());
        customer.setClientType(customerDto.getClientType());
        customer.setPriority(customerDto.getPriority());
        customer.setDisabled(customerDto.isDisabled());
        return customer;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public boolean isDisabled() {
        return disabled;
    }

    public void setDisabled(boolean disabled) {
        this.disabled = disabled;
    }

    public Character getClientType() {
        return clientType;
    }

    public void setClientType(Character clientType) {
        this.clientType = clientType;
    }

    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    @Override
    public String toString() {
        return "CustomerDto{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", userId='" + userId + '\'' +
                ", password='" + password + '\'' +
                ", clientType=" + clientType +
                ", priority=" + priority +
                ", disabled=" + disabled +
                '}';
    }
}
